@param int totalEstudantes
<!doctype html>
<html lang="pt-BR">
<head><meta charset="UTF-8">
    <title>Cadastro de estudantes</title>
    <link rel="stylesheet" href="/css/style.css">
</head>
<body>
    <img src="/images/ifpb-cajazeiras.png" alt="IFPB Campus Cajazeiras">
    <h1>Sistema de Cadastro de Estudantes</h1>
    <p>Estudantes cadastrados: ${totalEstudantes}</p>
    <a href="/estudantes/novo">Cadastrar estudante</a>
</body>
</html>

